name: Exemple Bonjour

on:
  push:
    branches: [ "main" ]

jobs:
  dire-bonjour:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher Bonjour
        run: echo "Bonjour"

      - name: Liste des fichiers
        run: ls -al