name: Configuration Java

on:
  workflow_dispatch:

jobs:
  affichage:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code soure
        uses: actions/checkout@v4

      - name: Configurer JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Afficher la version de JAVA
        run: java -version

      - name: Construire avec Maven
        run: mvn -B clean package -DskipTests

      - name: Afficher la version de maven
        run: mvn -version
#      - name: Sauvegarder les artefacts
#        uses: actions/upload-artifact@v4
#        with:
#          name: java-artifact
#          path: target/*.jar