name: Mise en place de l'intégration continue

on:
  workflow_dispatch:

jobs:
  codeql:
    runs-on: ubuntu-latest

    permissions:
      security-events: write # Pour la maj de l'onglet "Security and quality"
      contents: read

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configurer JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Tp5 : Ajouter l'utilisation de CodeQL
      - name: Initialiser CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java-kotlin

      - name: Construire avec Maven
        run: mvn -B clean verify -Dspring.profiles.active=test -Dmaven.test.failure.ignore=true

      - name: Génère le site Maven
        run: mvn site

      - name: Analyse avec CodeQL
        uses: github/codeql-action/analyze@v4

      # Tp6 : Ajouter l'utilisation de JaCoCo
      - name: Sauvegarde du rapport JaCoCo
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      # Tp7 : Ajouter l'utilisation de Checkstyle
      - name: Publier le rapport Checkstyle
        uses: actions/upload-artifact@v4
        with:
          name: rapport-checkstyle
          path: target/site/

      # Tp8 : Ajouter l'utilisation de SpotBugs
      - name: Publier le rapport SpotBugs
        uses: actions/upload-artifact@v4
        with:
          name: rapport-spotbugs
          path: target/spotbugsXml.xml