name: Mise en place de CodeQL

on:
  workflow_dispatch:

jobs:
  codeql:
    runs-on: ubuntu-latest

    permissions:
      security-events: write # Pour la maj de l'onglet "Security and quality"
      contents: read

    steps:
      - name: Récupération du code
        uses: actions/checkout@v4

      - name: Configurer JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Initialiser CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java-kotlin

      - name: Construire avec Maven
        run: mvn -B clean verify -Dspring.profiles.active=test -Dmaven.test.failure.ignore=true

      - name: Analyse avec CodeQL
        uses: github/codeql-action/analyze@v4



#      - name: Initialiser CodeQL
#        run: mvn -B clean verify -Dspring.profiles.active=test
#
#      - name: Sauvegarde du rapport JaCoCo
#        uses: actions/upload-artifact@v4
#        with:
#          name: jacoco-report
#          path: target/site/jacoco/
